import type { Metadata } from 'next';
import './globals.css';
import { GeistSans } from 'geist/font/sans';
import { Providers } from '@/components/providers';
import { WelcomeTutorial } from '@/components/welcome-tutorial';

export const metadata: Metadata = {
  title: {
    default: "System Kyron",
    template: "%s | System Kyron",
  },
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning className={GeistSans.className}>
       <head>
        <style>{`
          :root {
            --telecom-black: 228 14% 5%;
            --telecom-white: 0 0% 100%;
            --telecom-cyan: 183 100% 50%;
            --telecom-magenta: 318 100% 50%;
            --telecom-cyan-green: 158 100% 40%;
            --telecom-amber: 39 100% 50%;
            --telecom-pink: 337 100% 50%;
            --telecom-gray-1: 231 16% 10%;
            --telecom-gray-2: 230 11% 18%;
            --telecom-gray-3: 228 8% 25%;
            --telecom-gray-4: 240 4% 40%;
          }
        `}</style>
      </head>
      <body>
        <Providers>
            {children}
            <WelcomeTutorial />
        </Providers>
      </body>
    </html>
  );
}
