
import type {Metadata} from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { FirebaseClientProvider } from '@/firebase/client-provider';
import { GeistSans } from 'geist/font/sans';
import { Toaster } from '@/components/ui/toaster';
import WelcomeTutorial from '@/components/welcome-tutorial';

export const metadata: Metadata = {
  title: {
    default: "System Kyron",
    template: "%s | System Kyron",
  },
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning className={GeistSans.className}>
       <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className="font-sans antialiased">
        <FirebaseClientProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
            >
                <WelcomeTutorial />
                {children}
                <Toaster />
            </ThemeProvider>
        </FirebaseClientProvider>
      </body>
    </html>
  );
}
