
import {createLocalizedPathnamesNavigation} from 'next-intl/navigation';

export const locales = ['en', 'es'] as const;
export const defaultLocale = 'es';
export const localePrefix = 'always';

export const pathnames = {
  '/': '/',
  '/login': '/login',
  '/login-empresa': '/login-empresa',
  '/login-personal': '/login-personal',
  '/login-escritorio-juridico': '/login-escritorio-juridico',
  '/login-ventas': '/login-ventas',
  '/login-rrhh': '/login-rrhh',
  '/login-socios': '/login-socios',
  '/login-marketing': '/login-marketing',
  '/login-telecom': '/login-telecom',
  '/login-informatica': '/login-informatica',
  '/login-linea': '/login-linea',
  '/login-sostenibilidad': '/login-sostenibilidad',
  '/register': '/register',
  '/ecosistema': '/plataforma',
  '/dashboard': '/inicio',
  '/dashboard-empresa': '/dashboard-empresa',
  '/recursos-humanos': '/recursos-humanos',
  '/escritorio-juridico': '/asesoria-legal',
  '/analisis-ventas': '/analisis-ventas',
  '/punto-de-venta': '/punto-de-venta',
  '/tarjeta-digital': '/mi-perfil',
  '/tarjeta-reciclaje': '/mis-puntos',
  '/zero-risk': '/cumplimiento-total',
  '/recursos-fiscales': '/recursos-fiscales',
  '/gaceta-6952': '/consulta-gaceta',
  '/poderes-representacion': '/poderes-representacion',
  '/cuentas-por-cobrar': '/cobranzas',
  '/nominas': '/pagos-nomina',
  '/seguridad': '/ajustes-seguridad',
  '/notificaciones': '/avisos',
  '/declaracion-iva': '/declaracion-iva',
  '/islr-arc': '/reporte-islr',
  '/libro-compra-venta': '/libro-fiscal',
  '/venta-linea': '/activar-linea',
  '/mi-linea': '/mi-linea-5g',
  '/cierre-caja': '/cierre-caja',
  '/estrategias-ventas': '/estrategias-comerciales',
  '/facturacion': '/facturacion',
  '/facturacion-credito': '/ventas-credito',
  '/modelo-factura': '/modelo-factura',
  '/nota-debito': '/nota-debito',
  '/nota-credito': '/nota-credito',
  '/proformas': '/cotizaciones',
  '/estudio-factibilidad-economica': '/factibilidad-economica',
  '/estudio-poblacion': '/analisis-demografico',
  '/sector-privado-system-kyron': '/dossier-corporativo',
  '/manual-usuario': '/manual-usuario',
  '/identidad-marca': '/identidad-marca',
  '/mercado-ecocreditos': '/canje-puntos',
  '/generador-documentos': '/crear-contratos',
  '/academia-kyron': '/formacion',
  '/documentos': '/mis-documentos',
  '/partidas-nacimiento': '/partidas-nacimiento',
  '/actas-matrimonio': '/actas-matrimonio',
  '/documentos-judiciales': '/documentos-judiciales',
  '/antecedentes-penales': '/antecedentes-penales',
  '/directorio-medico': '/directorio-medico',
  '/manutencion': '/pago-manutencion',
  '/registro-rif': '/registro-rif-familia',
  '/sostenibilidad': '/sostenibilidad',
  '/ajuste-por-inflacion': '/ajuste-inflacion',
  '/analisis-caja': '/analisis-caja',
  '/cuentas-por-pagar': '/cuentas-pagar',
  '/analisis-rentabilidad': '/rentabilidad-pro',
  '/inventario': '/inventario',
  '/estructura-costos': '/estructura-costos',
  '/fidelizacion-clientes': '/fidelizacion-clientes',
  '/pasarelas-pago': '/pasarelas-pago',
  '/reports': '/reportes',
  '/tramites-fiscales': '/tramites-fiscales',
  '/analisis-mercado': '/analisis-mercado',
  '/analisis-riesgo': '/analisis-riesgo',
  '/billetera-cambio': '/billetera-cambio',
  '/acta-asamblea': '/acta-asamblea',
  '/activos-inmobiliarios': '/activos-inmobiliarios',
  '/autorizaciones': '/autorizaciones',
} as const;

export const {Link, redirect, usePathname, useRouter} = createLocalizedPathnamesNavigation({
  locales,
  localePrefix,
  pathnames
});
