
import {
  AlertTriangle,
  ArrowRight,
  BookUser,
  Bot,
  Briefcase,
  Building,
  Calculator,
  Check,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  ClipboardIcon,
  CreditCard,
  Download,
  FileBadge,
  FileText,
  Heart,
  HelpCircle,
  Image,
  Laptop,
  Link,
  Loader2,
  LogIn,
  LogOut,
  Moon,
  MoreVertical,
  PieChart,
  Pizza,
  Plus,
  Recycle,
  Rocket,
  Save,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Star,
  Sun,
  Trash,
  User2,
  UserPlus,
  Users,
  X,
  Zap,
  TabletSmartphone,
  ClipboardCheck,
  Send,
  Calendar,
  TrendingUp,
} from 'lucide-react';

export const Icons = {
  // General
  check: Check,
  close: X,
  right: ChevronRight,
  left: ChevronLeft,
  spinner: Loader2,
  add: Plus,
  login: LogIn,
  logout: LogOut,
  user: User2,
  users: Users,
  addUser: UserPlus,
  settings: Settings,
  help: HelpCircle,
  link: Link,
  moon: Moon,
  sun: Sun,
  laptop: Laptop,
  logo: Zap,

  // Sidebar
  dashboard: ClipboardIcon,
  transactions: ShoppingBag,
  accounts: Users,
  categories: Laptop,
  reports: FileText,

  // App specific
  alert: AlertTriangle,
  arrowRight: ArrowRight,
  bookUser: BookUser,
  bot: Bot,
  briefcase: Briefcase,
  building: Building,
  calculator: Calculator,
  checkCircle: CheckCircle,
  creditCard: CreditCard,
  download: Download,
  fileBadge: FileBadge,
  fileText: FileText,
  heart: Heart,
  image: Image,
  more: MoreVertical,
  pizza: Pizza,
  recycle: Recycle,
  rocket: Rocket,
  save: Save,
  scale: Scale,
  shieldCheck: ShieldCheck,
  star: Star,
  trash: Trash,
  pos: TabletSmartphone,
  reconciliation: ClipboardCheck,
  send: Send,
  calendar: Calendar,
  trendingUp: TrendingUp,
  pieChart: PieChart,
};
